### ISSUE TITLE
Add partners section to /s/index.tsx

### ISSUE THREAD

**Issue by weihanwang** [yuanjian-org/app#441]
Update <PartnersSection> in /s/index.tsx to add the following:

1. header: 参与机构
2. list all the logos and institution names that are listed at yuanjian.org/partners, excluding Tsinghua.
3. each GridItem should host one and only one institution. Create a reusable function to build these GridItems. Avoid repetitive code.

**Comment by lijunray** [comment]
Should I download the images into public/img? Or should I just use the image link directly?

**Comment by weihanwang** [comment]
> yuanjian.org/partners is blank for me, is it https://www.yjjxj.cn/partners?
> 
> Should I download the images into public/img? Or should I just use the image link directly?

download them into the repository.
