### ISSUE TITLE
Migrate user profiles

### ISSUE THREAD

**Issue by weihanwang** [yuanjian-org/app#487]
Go to https://www.notion.so/yuanjian/310209bce34a4dcf8d3c0bcdb828054c?v=5d7614a4241649a9ad2258c75d5090ef. For each user on the list:

## A. Migrate profile pictures

  1. If the user doesn't have a picture, skip.
  2. Find the user on https://mentors.org.cn/users and click on the user name. If the user already has profile picture, skip.
  3. Download the picture from notion and upload to the user profile page at mentors.org.cn

## B. Migrate profile text

  1. Copy ALL the relevant fields from notion to the user's profile page at mentors.org.cn, such as 性别、居住地、导师职业生活背景、导师生活爱好、自我介绍、and free text content on the notion page.
  2. NOTE, for users who already has rich profile content on mentors.org.cn, such as https://mentors.org.cn/mentors/e7ebf6b4-300a-419f-96ef-0ffe993fbe40, leave as is and do NOT overwrite existing content. For users whose profile content is thin on mentors.org.cn such as https://mentors.org.cn/mentors/6fc2f4bd-fb90-43bf-8efe-9af31df715d4, incorporate content from notion into and edit existing content on mentors.org.cn as you see fit.

**Comment by ada-only-one-ada** [comment]
Updated all mentors.
