### ISSUE TITLE
支持用微信账号登录

### ISSUE THREAD

**Issue by likawind** [yuanjian-org/app#77]
目前仅支持邮件验证码，我们可以考虑进一步支持一些中国较常见的验证方式，比如手机验证码和[微信OAuth网页授权](https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/Wechat_webpage_authorization.html)

目前我们的认证框架好像用的是authing，这个是他们关于手机登录的文档：https://docs.authing.cn/v2/reference/sdk-for-android/social/oneauth.html，微信授权的文档：https://docs.authing.cn/v2/reference/sdk-for-weixin-official-account.html

**Comment by weihanwang** [comment]
感谢你的建议！我们目前只支持email登录的原因是系统需要通过email与用户通信，因此email需要作为登录的基本途径。

@addlistener 不知 authing.cn 是否允许用户在用email登录后，绑定手机号或微信号？

**Comment by addlistener** [comment]
可以 https://docs.authing.cn/v2/reference/sdk-for-node/authentication/AuthenticationClient.html#%E7%BB%91%E5%AE%9A%E6%89%8B%E6%9C%BA%E5%8F%B7

**Comment by weihanwang** [comment]
We've migrated the app's auth system from authing.cn to next-auth. Here is next-auth's FR to support WeChat: https://github.com/nextauthjs/next-auth/discussions/6236

**Comment by addlistener** [comment]
@weihanwang check this out 

https://github.com/nextauthjs/next-auth/pull/10236

**Comment by weihanwang** [comment]
Example app: https://github.com/KaygNas/nextjs-auth-wechat
